### ISSUE TITLE
Incompatibility with libvlc < 2.0.6

### ISSUE THREAD

**Issue by GeertJohan** [jteeuwen/go-vlc#15]
Got the following compile error:
```
# github.com/jteeuwen/go-vlc
./player.go:706: cannot use C.int(s) (type C.int) as type C.uint in argument to _Cfunc_libvlc_video_set_spu
```

I'm using libvlc-dev 2.0.3-5+deb7u1

In version 2.0.6 the argument type was changed from `unsigned int` to `int`, according to http://upstream.rosalinux.ru/compat_reports/vlc/2.0.5_to_2.0.6/abi_compat_report.html

This means that since #2 was merged go-vlc is compatible with vlc 2.0.6+
Pre #2. go-vlc used an unsigned int, I'll create a reference comment in the commit to this issue.

This diff fixes for pre 2.0.6 (quite simple):
```diff
diff --git a/player.go b/player.go
index 48a9d61..6e364cc 100644
--- a/player.go
+++ b/player.go
@@ -698,12 +698,12 @@ func (this *Player) SubTileDescription() (TrackDescriptionList, error) {
 }
 
 // SetSubtitle sets the current subtitle track.
-func (this *Player) SetSubtitle(s int) (err error) {
+func (this *Player) SetSubtitle(s uint) (err error) {
 	if this.ptr == nil {
 		return syscall.EINVAL
 	}
 
-	if C.libvlc_video_set_spu(this.ptr, C.int(s)) != 0 {
+	if C.libvlc_video_set_spu(this.ptr, C.uint(s)) != 0 {
 		err = checkError()
 	}
```

I guess my question is: is there a good method to maintain compatibility with both versions?

**Comment by GeertJohan** [comment]
https://github.com/jteeuwen/go-vlc/commit/c7467aab9076dd5f2f022141307d2145386f2cf0#diff-e5eca29a9b39cab72ec32f93f054ee81L701

**Comment by GeertJohan** [comment]
Any thoughts on this?

**Comment by jteeuwen** [comment]
While your patch addresses incompatibility with the older libVLC version, I don't think merging it into master will help matters much, as it will effectively undo the patch you mentioned. Perhaps a separate branch for the older compatibility version is useful though.

**Comment by GeertJohan** [comment]
yes, or maybe keep this issue pinned until libvlc <2.0.6 has been phased out in most distro's.
