### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by ChrisMcKenzie** [jteeuwen/go-vlc#16]
I am little green to cgo so forgive me if this sounds dumb, but where should I put the vlc source if i wish to compile libvlc with my go build on osx? I feel like placing it in my src feels weird but maybe that is the best place.

Any help would be greatly appreciated.

**Comment by jteeuwen** [comment]
This code links against the shared library of VLC. So anywhere you would normally install libraries will do the trick. Along with the standard include/lib paths, the compiler will look for relevant parts here:

    // #cgo darwin  CFLAGS: -I/usr/local/include
    // #cgo darwin LDFLAGS: -L/usr/local/lib

**Comment by ChrisMcKenzie** [comment]
awesome yeah that make sense! thanks I have the demo working now just had to link the vlc sources to those paths.
